var glossary = {
"A": {
 "text": "<h2>A</h2><DL><DT><b>Adaptation Planning</b><DD>(tool function) Preparing a natural or urban area for the effects of climate change and extreme weather with the intention of reducing risk or exposure. Includes planning for current and expected future climates.<br><br><DT><b>Agriculture</b><DD>(developed environments) Farming; the practice of cultivating the soil, growing crops, and raising animals for food or other products.<br><br><DT><b>Air Quality</b><DD>(society) Measure of pollutants (or lack thereof) present in air; used to determine health and safety of atmosphere.<br><br><DT><b>Application</b><DD>(tag) The tool is an application.<br><br></DL>"},
"B": {
 "text": "<h2>B</h2><DL><DT><b>Buildings / Infrastructure</b><DD>(developed environments) Facilities, built systems, and structures built for permanent use. Examples include houses, buildings, roads, sewer systems, power lines, communication networks, among others.<br><br></DL>"},
"C": {
 "text": "<h2>C</h2><DL><DT><b>Carbon Emissions</b><DD>(weather and climate) The release of carbon (e.g., carbon dioxide or monoxide) gas into the atmosphere through direct (e.g., driving cars, shipping industry, airplanes, etc.) or indirect (e.g., food, textiles, etc.) means.<br><br><DT><b>Citizen Science</b><DD>(tool function) Involving public participation in data collection or other components of the scientific process.<br><br><DT><b>Climate Mitigation Planning</b><DD>(tool function) Reducing heat-trapping gasses in the atmosphere. May be accomplished by reducing sources (e.g., burning fossil fuels) or enhancing sinks (e.g., oceans, forests, soils).<br><br><DT><b>Climate projections</b><DD>(tag) The information in the tool contains possible future scenarios projected by climate models.<br><br><DT><b>Coastal</b><DD>(coastal / inland) Tools that consist of coastal topics.<br><br><DT><b>Compare scenarios/locations</b><DD>(tag) The tool allows the user to compare multiple scenarios or locations.<br><br><DT><b>Cost estimates</b><DD>(tag) The tool provides estimated costs.<br><br><DT><b>County level</b><DD>(tag) The information in the tool is at the county level.<br><br><DT><b>Cultural Resources</b><DD>(society) Any prehistoric or historic remains or indicators of past human activities, including artifacts, sites, structures, landscapes, and objects of importance to a culture or community for scientific, traditional, religious, or other reasons. Culture resources in this tool also encompass tools that illustrate recent/current human opinions, beliefs, or behaviors.<br><br></DL>"},
"D": {
 "text": "<h2>D</h2><DL><DT><b>Daily</b><DD>(tag) The data or tool is updated once a day.<br><br><DT><b>Dataset</b><DD>(tag) The tool is a dataset.<br><br><DT><b>Developed Environments</b><DD>(topic filter) An environment that was developed by humans for economic or social benefits.<br><br><DT><b>Downloadable data</b><DD>(tag) The tool allows data to be exported or downloaded.<br><br><DT><b>Downloadable results</b><DD>(tag) The analyzed results (including a narrative, report, graph, or data) from the tool can be downloaded.<br><br><DT><b>Drought</b><DD>(weather and climate) Period of abnormally dry weather marked by little or no rain that lasts long enough to cause water shortage for people and natural systems.<br><br></DL>"},
"E": {
 "text": "<h2>E</h2><DL><DT><b>Eco Services Valuation</b><DD>(ecosystems) Quantifying the benefits that humans receive from natural systems; often utilizes economic value.<br><br><DT><b>Economic Assessment</b><DD>(developed environments) Tools that calculate and evaluate potential costs and benefits.<br><br><DT><b>Ecosystems</b><DD>(topic filter) A community of all living things and non-living things (e.g., air, soil, water, and sunlight) that interact with each other in a specific environment.<br><br><DT><b>Engagement</b><DD>(tool function) Tools or guidance to support community engagement in climate impact assessment and/or planning.<br><br></DL>"},
"F": {
 "text": "<h2>F</h2><DL><DT><b>Fisheries and Aquaculture</b><DD>(developed environments) The breeding, rearing, and harvesting of fish, shellfish, and other aquatic animals and plants for food or other products.<br><br><DT><b>Forecast</b><DD>(tag) The information in the tool contains short-term estimates of predictions.<br><br><DT><b>Forestry</b><DD>(developed environments) Science and practice of planting, managing, and caring for forests.<br><br></DL>"},
"G": {
 "text": "<h2>G</h2><DL><DT><b>Grid based</b><DD>(tag) The information in the tool is gridded and may not be bound by jurisdiction boundaries (i.e., cities, counties, states).<br><br></DL>"},
"H": {
 "text": "<h2>H</h2><DL><DT><b>High</b><DD>(skill level) The tool requires extensive additional effort on the users part to understand how to use the tool or may require collecting data or conducting new research.<br><br><DT><b>High Tide / Recurrent Flooding</b><DD>(water / flooding) Tools with information about high tide flooding or flooding that occurs repeatedly in an area from precipitaion, high tides, or storm surge.<br><br><DT><b>Historical </b><DD>(tag) The information in the tool covers the historical time period.<br><br></DL>"},
"I": {
 "text": "<h2>I</h2><DL><DT><b>Identify Vulnerabilities</b><DD>(tool function) Identifying community assets (e.g., critical infrastructure and natural resources) and people at risk to extreme weather and climate-related hazards.<br><br><DT><b>Inland Flooding</b><DD>(water / flooding) Flooding that occurs hundreds of miles away from the coast.<br><br><DT><b>Interactive interface/map</b><DD>(tag) The tool is interactive.<br><br></DL>"},
"J": {
 "text": "<h2>J</h2><DL><DT><b>Jursidiction based</b><DD>(tag) The information in the tool is bound by jurisdiction boundaries (i.e., cities, counties, states).<br><br></DL>"},
"K": {
 "text": "<h2>K</h2>"},
"L": {
 "text": "<h2>L</h2><DL><DT><b>Location specific</b><DD>(tag) The information in the tool is specific to one or more locations.<br><br><DT><b>Low</b><DD>(skill level) The tool is easily accessible with little or no additional effort on the user to understand how to use the tool.<br><br></DL>"},
"M": {
 "text": "<h2>M</h2><DL><DT><b>Med</b><DD>(skill level) The tool requires some additional effort on the users part to understand how to use the tool or may require mining existing data.<br><br><DT><b>Monthly</b><DD>(tag) The data or tool is updated every month.<br><br></DL>"},
"N": {
 "text": "<h2>N</h2><DL><DT><b>Noncoastal/ Inland</b><DD>(coastal / inland) Tools that consist of noncoastal or inland topics.<br><br></DL>"},
"O": {
 "text": "<h2>O</h2><DL><DT><b>Open source</b><DD>(tag) The source code or data for the tool is freely available.<br><br></DL>"},
"P": {
 "text": "<h2>P</h2><DL><DT><b>Planning / Land Use</b><DD>(developed environments) Process of designing or regulating how an area of land is used. Often this is done to promote certain economic, social, or environmental benefits.<br><br><DT><b>Precipitation</b><DD>(weather and climate) Rain, snow, sleet, and hail are types of precipitation.<br><br><DT><b>Process Support</b><DD>(tool function) Formal ways of thinking about the means by which decision are made, as opposed to computational or modeling methods used to support decision making' (RAND).<br><br><DT><b>Program</b><DD>(tag) The tool contains multiple applications, datasets, spreadsheets, or sources of information.<br><br><DT><b>Public Health</b><DD>(society) Tools that assess the physical, social, and mental wellbeing of a community.<br><br></DL>"},
"Q": {
 "text": "<h2>Q</h2><DL><DT><b>Quarterly</b><DD>(tag) The data or tool is updated quarterly.<br><br></DL>"},
"R": {
 "text": "<h2>R</h2><DL><DT><b>Real-time/Current</b><DD>(tag) The information in the tool is real-time or current to today or the past few days.<br><br><DT><b>Regional level</b><DD>(tag) The information in the tool is at the regional level.<br><br><DT><b>Registration required</b><DD>(tag) The tool requires you to register before using the tool or to get additional features.<br><br><DT><b>Restoration</b><DD>(ecosystems) The act or restoring or converting something to a previous condition.<br><br><DT><b>Restrictions apply</b><DD>(tag) The tool requires software requirements or other requirements to use or participate.<br><br></DL>"},
"S": {
 "text": "<h2>S</h2><DL><DT><b>Saltwater Intrusion</b><DD>(water / flooding) The movement or flooding of saltwater onto normally dry land or into freshwater aquifers, rivers, estuaries, wetlands, and lakes.<br><br><DT><b>Sea Level Rise</b><DD>(weather and climate) Increase in water level caused in part by melting land-based ice and expanding water. Exacerbates existing coastal hazards such as flooding, erosion, inundation, and extreme events. Often abbreviated to SLR.<br><br><DT><b>Shorelines and Erosion</b><DD>(ecosystems) Tools that include information about shorelines and erosion. Erosion is the breakdown and transportation of soil, rock, and other dissolved material by wind, water, chemical interactions, and other natural processes.<br><br><DT><b>Social Vulnerability</b><DD>(society) Tools that assess the resilience of a community impacted by climate or other natural hazards.<br><br><DT><b>Society</b><DD>(topic filter) Tools that cover topics that impact a community collectively via health, air quality, or social vulnerability.<br><br><DT><b>Soils</b><DD>(ecosystems) Tools that include information about soil.<br><br><DT><b>Solutions</b><DD>(tag) The tool provides one or more solutions.<br><br><DT><b>Spreadsheet</b><DD>(tag) The tool is a spreadsheet.<br><br><DT><b>State level</b><DD>(tag) The information in the tool is at the state level.<br><br><DT><b>Storm Surge</b><DD>(water / flooding) A coastal flood caused by rising water level from a storm.<br><br><DT><b>Storms and Hurricanes</b><DD>(weather and climate) Tools that include information about hurricanes and other types of storms.<br><br><DT><b>Stream Flow</b><DD>(water / flooding) The amount of water flowing through a stream or river.<br><br><DT><b>Subdaily</b><DD>(tag) The data or tool is updated several times a day.<br><br><DT><b>Submerged Aquatic Vegetation</b><DD>(ecosystems) A plant that grows completely under the water.<br><br></DL>"},
"T": {
 "text": "<h2>T</h2><DL><DT><b>Temperature</b><DD>(weather and climate) Tools that include temperature information.<br><br><DT><b>Toolkit/Tool Collection</b><DD>(tool function) A program or data center providing multiple tools.<br><br><DT><b>Transportation</b><DD>(developed environments) System (e.g., bus, roadways, subways, etc.) for moving passengers or goods from one place to another.<br><br></DL>"},
"U": {
 "text": "<h2>U</h2>"},
"V": {
 "text": "<h2>V</h2><DL><DT><b>Varies</b><DD>(skill level) Applies to a tool collection where multiple tools vary in the level of effort required on the user.<br><br><DT><b>View Future Projections</b><DD>(tool function) Visualizing or comparing possible future scenarios projected by climate models.<br><br><DT><b>View Past/Current Conditions</b><DD>(tool function) Visualizing or comparing historical and/or present-day conditions.<br><br></DL>"},
"W": {
 "text": "<h2>W</h2><DL><DT><b>Water / Flooding</b><DD>(topic filter) Tools related to water level and quality, as well as various types of flooding.<br><br><DT><b>Water Level</b><DD>(water / flooding) Tools containing information about water levels of a strea, river, lake, or ocean. Also known as gauge height or stage.<br><br><DT><b>Water Quality</b><DD>(water / flooding) Chemical, physical, and biological condition of water, with respect to a particular purpose (e.g. drinking or swimming).<br><br><DT><b>Watershed level</b><DD>(tag) The information in the tool is at the watershed level.<br><br><DT><b>Weather and Climate</b><DD>(topic filter) Weather is day-to-day changes in atmospheric conditions. Climate is weather conditions of a region averaged over a long period of time.<br><br><DT><b>Website</b><DD>(tag) The tool contains information as a website. It may or may not be interactive.<br><br><DT><b>Weekly</b><DD>(tag) The data or tool is updated every week.<br><br><DT><b>Wetlands</b><DD>(ecosystems) Tools that include information about wetlands.<br><br></DL>"},
"X": {
 "text": "<h2>X</h2>"},
"Y": {
 "text": "<h2>Y</h2><DL><DT><b>Yearly</b><DD>(tag) The data or tool is updated on a yearly basis.<br><br></DL>"},
"Z": {
 "text": "<h2>Z</h2>"}
}
